config/routes.rb
Rails.application.routes.draw do
  get "tasks", to: "tasks#index"
  get "tasks/:id", to: "tasks#show", as: "task"
  get "new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params['id'])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<ul>
  <h1>My tasks</h1>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task.id) %></li>
  <% end %>
</ul>
<%= link_to "newTask", new_path %>

app/views/tasks/new.html.erb
<h1><%= link_to "back to tasks", tasks_path %></h1>

<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.number_field :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= link_to "back to tasks", tasks_path %></h1>

<h1><%= @task.title %></h1>
<h1><%= @task.details %></h1>
<h1><%= @task.completed %></h1>